### ISSUE TITLE
Freie Satellitenbilder in STU

### ISSUE THREAD

**Issue by Bielhelm** [usox/stu3#10]
Um mehr Pep in die Grafiken zu bringen, könnte man sog "freie Satellitenbilder" teilweise benutzen, um die einzelnen Sachen realistischer darzustellen. 
(Nach FOSSGIS 2017 darf jeder diese freien Bilder 
sogar für kommerzielle Sachen verändern und benutzen)
https://av.tib.eu/media/30501 
https://openmaptiles.com/satellite/

**Comment by usox** [comment]
Ist das im Assets-Repo nicht besser aufgehoben?

**Comment by Bielhelm** [comment]
Ok. Dann kommt das da hin.
