### ISSUE TITLE
Nicht erforschte Gebäude durch html manipulation baubar

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#12]
Vorrausgesetzt man hat die Gebäude ID eines Gebäudes welches man noch nicht erforscht hat, kann man einfach durch ersetzen dieser ID im Browser bei einem vorhandenen Gebäude die html so manipulieren, dass man dann dieses Gebäude bauen kann.

**Comment by usox** [comment]
Du hast damit wirklich einen Bauauftrag erstellen koennen?

**Comment by usox** [comment]
Das Problem besteht nur dann, wenn gerade daran geforscht wird. Es wird nicht geprueft, ob die Forschung bereits abgeschlossen ist. Problem ist hier https://github.com/usox/stu3/blob/ec48c8605a0e1c2e4333ca24cf835e0752f846e5/src/class/user.class.php#L320
