### ISSUE TITLE
Selbstzerstörung des Schiffes defekt

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#15]
Nach eingabe des Selbstzerstörungscodes wird man auf die Schiffsseite geleitet. Dort steht dann die Meldung "Die Selbstzerstörung wurde durchgeführt". Dass Schiff jedoch, existiert weiterhin.

**Comment by usox** [comment]
Fixed mit 868e07c0f39afb8579da83960e3659ec45b4c152
