### ISSUE TITLE
Akademie-Gebäude fehlt

### ISSUE THREAD

**Issue by usox** [usox/stu3#16]
Es gibt zwar Forschungen für die `Akademie`, jedoch gibt es zur Zeit kein Gebäude weshalb auch keine Crew-Ausbildung möglich ist.

Folgende Dinge sollten daher mal erarbeitet werden:
- Namen der Akademie-Gebäude für die einzelnen Rassen (ggf. auch Anpassungen der Forschungsbezeichnungen)
- Auf welchen Feldern baubar?
- Werte der Akademie-Gebäude (Energieverbrauch, Arbeiter, Warenverbrauch)
- Baukosten
- Bilder

**Comment by LWU86** [comment]
Keine Arbeit am Code dabei? Dann klingt das nach nem Projekt für mich^^

Dazu die Frage: Wie final sind die Werte in puncto Energie-, Waren- und Arbeiterverbrauch? Kann man sich daran schon orientieren oder werden die nochmal massiv überarbeitet?

**Comment by Bielhelm** [comment]
Einzelne Rassennamen vorgeschlagen:
- Föderationsakademie
- Klingonisches Kriegerinstitut
- Romulanische Imperiale Akademie
- Ferengi Handelsuniversität
- Cardassianische Millitärakademie

Empfehlung auf Bau auf Wiese, Ödland, Wüste, Eisfläche
(da in 2.6 ähnliches nur auf Wiese und Ödland ziemlich schwer hinzukriegen war)

**Comment by usox** [comment]
@LWU86 Ich gehe davon aus, dass saemtliche Werte nicht final sind. Es ist demnach aber auch kein Problem, diese zu aendern. Ich denke, bei den Werten geht es erstmal um eine grobe Richtung um zu erkennen, was Sinn und keinen Sinn macht und ob z.B. Warenverbrauch/Kosten ueberhaupt erfuellbar sind (z.b. wenn die Akademie Antimaterie verbraucht, man aber noch keine herstellen kann)

**Comment by LWU86** [comment]
Alles klar. Ich werd dann mal nen Konzept erarbeiten (und dabei Bielies Namen klauen^^) und mich zwecks Bildern mit Hux zusammensetzen.

**Comment by LWU86** [comment]
**Arbeiterverbrauch**: -25 <-- Liegt über dem Verbrauch des Forschungszentrums, aber unter dem bis dato arbeiterintensivsten Wirtschaftsgebäude, was mir durchaus zweckdienlich scheint.
**Energieverbrauch**: Der sollte recht hoch angesetzt werden, da die Akademie wahrscheinlich eins der wichtigsten Gebäude im Spiel sein wird. Daher tendiere ich zu -12 bis -15
**Warenverbrauch**: Du hast es schon angesprochen: Nur Waren, die schon produziert werden können, machen Sinn. Da die Akademie auf die Ausbildung von Leuten abzielt, würde die Logik gebieten, daß Nahrung verbraucht wird. Aber nicht zu viel davon. Ich würde -2 bis -3 sagen.

Die **Baukosten** würde ich an das höchststufige Forschungszentrum anlehnen. Hier kann ich aber noch keine Zahlen nennen, da ich die aktuellen Werte noch nicht kenne ;)

Die **Felder**, die Bielie erwähnt hat, sind schon ganz gut. Ich würde aber auf jeden Fall die aufgeschüttete Fläche noch dazunehmen. Eventuell auch gesprengte Berge.

**Comment by usox** [comment]
So, ich habe das Gebäude mal für alle drei Rassen testweise eingefügt - Pain in the ass! Bau- und Betriebskosten gibts noch keine, da das haendisch ein Albtraum ist.
