### ISSUE TITLE
Kartenfeld mit zerstörtem Schiff nicht anfliegbar

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#17]
Nachdem ich ein Schiff bei den Koordinaten 72|89 selbst zerstört habe, ist diese Koordinate nichtmehr anfliegbar. Wenn man drauf möchte, kommt man auf eine weiße Seite mit der Fehlermeldung "Object not found exception - Object: 8; call: NA"

**Comment by usox** [comment]
Problem war, dass die für Schiffswracks vorgesehene Schiffs-Klasse gefehlt hat. Ich muss mal schnell was bauen, mit dem man sich die anlegen lassen kann.

**Comment by usox** [comment]
Wird in die nächte Version des base-dumps aufgenommen
