### ISSUE TITLE
"Invalid param exception: fid" bei linkem oberen Orbitfeld

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#19]
Bei meinen Kolonien erscheint beim anklicken des linken oberen Orbitfeldes, komischerweise Nebel Feld 1, die Fehlermeldung "Invalid param exception: fid". Es lässt sich ebensowenig auf dem Feld etwas bauen. Scheint als würde erst ab dem zweiten Feld aufwärts gezählt werden.

**Comment by usox** [comment]
Problem ist vermutlich, dass wir bei `0` anfangen und ein Sicherheitsmechanismus greift der da sagt, `0 ist keine valide Zahl`.
