### ISSUE TITLE
Bau kann nicht abgebrochen werden nachträglich

### ISSUE THREAD

**Issue by Bielhelm** [usox/stu3#22]
Der Bau eines Gebäude (in diesem Fall) Deuteriumsynthezier, kann nicht mehr abgebrochen werden, sobald initiiert. Das sollte zumindest eine kurze Zeitspanne nach dem Anstarten noch möglich sein oder gegen Kosten abgebrochen werden können.

**Comment by Huxinator** [comment]
Gerade bei mir getestet. Auch mit einem Deuteriumsyntheziser. Ich kann nachdem ich einen Bauauftrag gegeben habe, das ding ganz normal demontieren und bekomme Ressourcen zurück.

**Comment by Bielhelm** [comment]
Warte mal. "Demontieren" => "Bau abbrechen" - ok- closed
