### ISSUE TITLE
Bonusfeldicon als eigene "Ebene" anzeigen

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#23]
Momentan haben die Felder welche einen Bonus haben wie doppeltes Deuterium, doppeltes Tritanium usw. auf ihrem Feldhintergrund ein kleines Icon drauf. Damit dieses Icon sichtbar bleibt, wenn ein Gebäude auf dieses Feld gebaut wird, werden für diese Gebäude dort extra Grafiken angefertigt mit einem kleinen "transparentem Rechteck" an der Stelle an der eigentlich das Icon wäre, damit eben dieses aus dem Feldhintergrund sichtbar ist. 

Wäre es nicht einfacher diese Icons seperat in einer Ebene über dem Feld bzw. ggf. über dem Gebäude einfach drüber zu legen? Das würde uns ersparen jedes Gebäude Bild nachträglich zwei mal zu bearbeiten um dieses kleine Rechteck mit verschiedenen Rahmen einzubauen.

**Comment by usox** [comment]
Muss man mal schauen. Problematisch ist es nur daher, dass fuer die GUI da einiges an Anpassungen (z.B. auch beim Bauemenue) gemacht werden muessen - da dort eh schon drei Layer uebereinander liegen, koennte es einfach komplexer werden.
Ich werde mir das mal bei Gelegenheit ansehen, man koennte aber auch ueberlegen, ob man z.B. diese Bilder einfach generieren laesst. Mal gucken...

**Comment by Bielhelm** [comment]
Die Terraforming Bilder werden vorerst direkt nach der Veröffentlichung der neuen Fields-Bilder (die ich mache) von violentviper (entsprechend den Vorgaben) bearbeitet werden, soweit habe ich mich mit ihm geeinigt. Sicherlich ist das ganz nur ein Test, jedoch wird auch das wieder einige Zeit in Anspruch nehmen. Darum wäre es schön zu wissen, ob das ganze dann auch so bleibt, oder eh nur als Test zum reinarbeiten angesehen wird.

**Comment by usox** [comment]
Ich werde mir das mit der Kolonieoberflaeche und dem Baumenue die Tage mal ansehen und dann gibts Feedback.

**Comment by usox** [comment]
Problem wurde jetzt mit einem Generator sowie anders strukturierten Assets geloest
