### ISSUE TITLE
Fehlende orbitale Wartung deaktiviert Orbitalgebäude nicht

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#24]
Ich hab zwei Gebäude im Orbit welche mir dementsprechend insgesammt -2 orbitale Wartung pro Tick ziehen. Ich hab mal testweise vor zwei Ticks den Raumbahnhof deaktiviert damit ich insgesammt auf der Kolonie einen Malus von orbitaler Wartung habe. Dennoch werden die Gebäude beim Tick trotz des Malus nicht deaktiviert.

**Comment by usox** [comment]
Das ist spannend

**Comment by usox** [comment]
@Huxinator Sicher, dass der Tick fuer die Kolonie lief? Ich habe festgestellt, dass der aufgrund eines Bugs nicht alle Kolonien bearbeitet hat

**Comment by Huxinator** [comment]
Ich bin mir unsicher aber ich glaube, dass ich den Raumbahnhof bereits vor 22 Uhr deaktiviert hatte.
Aber sicher bin ich mir da nicht.

Aber hat sich wohl geklärt. Hat sich gerade alles deaktiviert.

**Comment by usox** [comment]
Ich vermute, dass seit 21 Uhr keine (vollstaendigen) Kolonieticks liefen
