### ISSUE TITLE
Weiße Seite beim Modul herstellen - Falsche Module?

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#25]
Im Modulherstellungsmenü(Hauptsysteme) kann man zwar die Anzahl der Module welche man herstellen möchte auswählen, jedoch gelangt man nach dem man auf dem herstellen Button geklickt hat auf eine weiße Seite.

Weiterhin kann ich bei dem Gebäude für die Hauptsysteme Schilde und Hülle bauen. Das scheint mir irgendwie eher Defensivsystem zu sein, statt Hauptsystem.

**Comment by Huxinator** [comment]
Für letzteres waren wohl die Funktionen bei den Modulgebäuden zwischen Hauptsystem und Defensivsystem in der DB vertauscht. Hab das dementsprechend angepasst.

**Comment by usox** [comment]
#26
