### ISSUE TITLE
Deaktivierter Raumbahnhof und Jägerwerft können Shuttles bauen

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#30]
Trotz dessen, dass der Raumbahnhof und die Jägerwerft deaktiviert sind, lassen sich über beide Gebäude ganz normal Shuttles der Icarus Klasse bauen sowie auch zumindest vom Raumbahnhof starten.
Die Jägerwerft zeigt fertige Shuttles die gestartet werden könnten garnicht erst an. Vermutlich aber, weil die Shuttles (egal ob im Orbit oder auf dem Planeten erbaut) lediglich von der Oberfläche starten sollen.

**Comment by usox** [comment]
Ich vermute, dass das im Code noch nicht geprueft wird. Zudem ist das ein grundsätzliches Problem. Früher waren Werften und Raumbahnhof nicht aktivierbar, da gabs das Problem nicht. Jetzt kann man ja auch den Verbrauch/Effekt von Werften/Raumbahnhoefen austricksen. Ich denke, man wird etwas ueberlegen muessen...

**Comment by Huxinator** [comment]
Ich geh mal davon aus, dass der Schiffsbau später auch einige Zeit dauern würde. Dementsprechend kann eine deaktivierung des Gebäudes zumindest während der Bauzeit dafür sorgen, dass der Bau entweder unterbrochen oder gar abgebrochen wird. Bei letzterem Würde man dann auch die eingesetzten Ressourcen/Module schlichtweg verlieren als "Bestrafung". Dann sollte man auch zumindest dafür sorgen, dass der eigene Raumbahnhof ebenso immer läuft und nichts durch Energiemangel deaktiviert wird.

**Comment by usox** [comment]
Muss man schauen. Wenn es längere Tickpausen gibt (z.b. ueber Nacht), dann koennte das zum Problem werden, wenn man da mit echter `Bauzeit` arbeitet. Eine Moeglichkeit waere `wird zum nächsten Tick fertig` wie bei der Crew - dann koennte man das besser steuern.

**Comment by usox** [comment]
Also ich habe mal ein wenig nachgeschaut und ueberlegt.

Der Start und Bau einfachster Schiffe beim Raumbahnhof ist als sekundär-Funktionalität zu sehen. Heisst, diese kann eigentlich auch bei einem deaktivierten Gebäude möglich sein.
Der eigentliche Schiffbau wird tatsächlich unterbrochen, wenn die Werft deaktiviert wird. Wird diese wieder aktiviert, wird der Bau fortgesetzt.
Unter diese Prämisse kann ich damit leben...
