### ISSUE TITLE
Allianz-Verwaltung Schiffsliste leer

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#33]
In der Allianz-Verwaltung werden die Schiffe eines Users nicht angezeigt. Stattdessen steht dort einfach nur "fill me"

**Comment by usox** [comment]
Ich schaetze, das wurde noch nicht implementiert

**Comment by usox** [comment]
Eine kleine Liste kam mit 0c21b7fcd1c676dfa94d7ccadbf686943a2eb2c2 rein
Erstmal ok...
