### ISSUE TITLE
Verschiedene Farbskins

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#34]
Man könnte wie früher wieder diverse Farbskins für STU anbieten. Damals gabs da ja solche Sachen wie Klingonen, LCars, Dominion usw.
Prinzipiell müsste man ja nur die .css Datein dementsprechend ändern und irgendeine Funktion in den Einstellungen wieder einbauen um ein Skin auszuwählen.

**Comment by usox** [comment]
Halte ich nicht fuer sinnvoll, war damals schon ein riesen Mist weil staendig irgendwas nicht gepasst hat. Ich wuerde da lieber bei einem Skin bleiben und habe auch schon den Support dafuer ausgebaut (genauso wie fuer eigene Grafikpacks)
