### ISSUE TITLE
Fehlender Frachter Bauplan in Werft

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#38]
Frachtschiffe lassen sich nach der Erforschung der Fregattenwerft erforschen. Da es keine eigene Frachterwerft gibt, sollte man davon ausgehen, dass Frachtschiffe in dieser Werft auch baubar sind.
Leider wird der Bauplan in der Fregattenwerft nicht angezeigt.

**Comment by usox** [comment]
False positive....
