### ISSUE TITLE
Schiffsbaumenü führt zur Fehlermeldung

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#39]
Wenn man ein erforschtes Schiff (in meinem Fall eine Fregatte der Aegian Klasse) bauen möchte, und in der Fregattenwerft auf den jeweiligen Bauplan klickt, kommt man auf eine weiße Seite mit der Fehlermeldung:

PHPTAL Exception

This page cannot be displayed.

Enable display_errors to see detailed message.

**Comment by usox** [comment]
Sollte jetzt funktionieren
