### ISSUE TITLE
Crew ab Spielstart erzeugen

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#42]
Sollte man Usern gleich zu beginn die Möglichkeit geben Schulen zu bauen?
Man würde damit direkt am Anfang an das Crewsystem herangeführt werden. Die Spieler könnten somit dann ihre Crew an Schulen ausbilden und damit auch ihr Kolonisationsschiff bemannen sowie einen möglichen ersten Frachter.

**Comment by usox** [comment]
Eine andere Idee wäre es, dem Startgebäude (Koloniezentrale) gleich einen Zufriedenheits-Effekt mitzugeben

**Comment by Bielhelm** [comment]
Wäre alles möglich, aber ist das "ab Anfang an" schon ratsam für jeden, der mal in STU reinschnuppern möchte? Es ist ohnehin schon relativ anspruchsvoll. Das kann man doch alles erst ab einem gewissen Stand ingame sinnvoll einsetzen. Was bringt es euch, wenn die Leute davorsitzen, wird der Ochs vorm Berg, weil es einfach zu kompliziert ist, da Dinge abzuschalten, hier zwingend anzuschlaten, die dann wieder irgendwann abgeschaltet werden müssen um die Zufriedenheit ala 1.5 zu erhöhen? Warum ist die "Sympathie" eigentlich rausgeflogen aus STU?

**Comment by Huxinator** [comment]
Die Komplexibilität war ja immer das, was STU ausgezeichnet hat. Viele kleine Zahnräder im Getriebe von STU haben die Leute begeistert. Und nicht so ein einfaches dahingeklatschtes Ding wie v2.6

**Comment by usox** [comment]
Ich sehe weniger ein Problem damit, wenn die Koloniezentrale schon einen Primäreffekt für die Crewberechnung erzeugt. Wenn man ehrlich ist muss man feststellen, dass die ersten Tage und Wochen eine recht langatmige Geschichte sind bei der man wohl kaum überfordert sein kann. Daher macht es sicher Sinn, hier schon grundlegende Konzepte wie `Crew` zu vermitteln, ohne dafür extra Gebäude zu brauchen. Diese kommen später im Rahmen der Forschung - das passt dann.

Sympathie war ein altes Konzept und aufgrund seiner Beschaffenheit im einem Multi-Rassen-Szenario nicht wirklich sinnvoll - Wirtschaft war es schon eher. Wirtschaft hatte aber das Problem, dass es an Produktion gekoppelt war und somit ein ständiger Warenzuwachs herrschte. Die Primär- und Sekundär-Effekte haben dieses Problem nicht, müssen jedoch gut ausbalanciert werden...

**Comment by Huxinator** [comment]
Akademiegebäude ist jetzt ab dem selben Zeitpunkt erforschbar wie das erforschen der ersten Schiffsklasse welche Crew benötigt. Mit der Akademie kann man also die erste Crew erzeugen sowie auch ausbilden.
