### ISSUE TITLE
Forschungen für höhere Modullevel fehlen

### ISSUE THREAD

**Issue by usox** [usox/stu3#53]
Derzeit fehlen die Forschungen für höhere Modullevel. Am besten, wir fügen die mal ein und schauen, wie weit wir kommen. Später müssen die Forschungen an die Kosten der Module ausgerichtet werden, derzeit ist aber noch egal.

**Comment by Huxinator** [comment]
Done
- Klasse 1 Module erscheinen nach der erforschung der jeweiligen Modulfertigung
- Klasse 2 Module ebenso und müssen dann noch zusätzlich erforscht werden
- Klasse 3 und 4 Module erscheinen nach der erforschung der jeweiligen Modulfabrik und müssen dann noch erforscht werden
- Klasse 5 und 6 Module erscheinen nach der erforschung des jeweiligen Modulkomplexes und müssen dann noch erforscht werden
