### ISSUE TITLE
Nebelnamen gesucht

### ISSUE THREAD

**Issue by usox** [usox/stu3#58]
Aktuell gibt es 31 Nebel auf der Karte, die gerne einen Namen haben möchten.

Feel free :)

**Comment by LWU86** [comment]
Hast du noch mal den Link zur Karte?

**Comment by usox** [comment]
Puh ne, direkt gerade nicht.....

**Comment by Bielhelm** [comment]
Eine Liste ausgesuchter möglicher Ideen aus der Wiki für echte Nebelnamen in der Galaxis (soweit nicht anders beschrieben (jeweils: - am Wortstamm heisst: Nebel hintendran hängen) (alternativ: ging sicher auch -Haufen, -Helm, - Kaskade, - Geist, - Wolke, -Gestirn,  - Cluster, -Gürtel, -Ausdehnung)

https://de.wikipedia.org/wiki/Liste_von_Eigennamen_von_Deep-Sky-Objekten
--> Eigennamen von Deep Sky Objekten/WIKI 

- Spinnen-, Katzenaugen-, Schneeball-, Krebs-, Schmetterling-, Thors Helm, Kokon-, Lagunen-, Pferdekopf-, Herz-, Barnards Ring, Blasen-, Sichel-, Flammen-, Pfeifen-, Tintenklecks-, Adler-, Bärenklau-, Cirrus-, Elefantenrüssel-, Enten-, Feuerrad, Hexenkopf-, Helix-, Hyaden, Triaden-, Plejaden, , Kembels Kaskade, Kleiderbügelhaufen, Kohlensack, Krabben-. Medusa-, Preaesepe, Schleier- , Siebengestirn, Stundenglas- , 

unter anderen: 

http://mrklingo.freeshell.org/romulan/engtorihan.html
https://memory-alpha.fandom.com/de/wiki/Ferengi_(Sprache)
https://theally.userboard.org/die-sprache-f25/worterbuch-deutsch-kardasi-t65.html
usw. 

Mehr Födi Eridan- , Stella- , Arucanis-, Delta Volanis-; 
Mehr Card : Betreka- ,  Corrosive- ; Badlands, Orcu-; Hulimrek-; Praza-; Atarek-; Atarital,_; Terad-; 
Mehr Kling: Yan, Rolor- , Mutara-; Khazan-; B´Tran-;  T'Ong-;; D'kel ; Azlesa-;
Mehr Romi : Afehirr-, Azure-, Hromi, Zenas-; Mnei´sahe-; Nuhur-;  Grukhai-; Kaidha-; Mosaram-; Jaeih- ; usw..
Mehr Ferengi: Oumox-; Yoba-; Glebbening-; NanDi-; Tovat-; Gleep-;

**Comment by LWU86** [comment]
Ha, hab die Karte wiedergefunden. https://cdn.discordapp.com/attachments/602151824123756576/614376966606290947/karte.jpg
Die farbig umrandeten Gebiete sind ja die der Rassen. Wenn ihr mir sagt, wo Fergs und Cardis später angesiedelt werden sollen, werd ich die entsprechend benennen.

**Comment by Huxinator** [comment]
Ich glaube wir sollten erstmal nur nach den drei Rassen gehen, sollten die Ferengi und Cardis bis zur Beta rein kommen, stand ja sowieso die Idee im Raum eine neue, etwas größere Karte zu generieren. Dann wirds vermutlich den ein oder anderen Nebel mehr geben, den man benennen kann.

**Comment by LWU86** [comment]
Lacaertenebel, Tartaruswolke, Afehirrschleier, Zenashaufen, Eridunebel, Fornacisnebel, Eridancluster, Draconisnebel, Geminorumkaskade, Atargatiswolke, Imhotep-Nebel, Spinnencluster, Mosaramkaskade, Yumestacluster(*), Helixwolke, Golf von Penobscot(*), Kalvelisnebel, Bharanikaskade, Lyraenebel, Aurumnebel, Argentumnebel, Feuerradwolke, Khazancluster, B'Tran-Nebel, Azlesanebel, T'Ongwolke, Rolornebel, Yankaskade, D'Kel-Wolke.
30 Stück zähl ich nur auf der Karte. Keine Ahnung, welcher von dir als zwei und von mir als einer interpretiert wird.
![Nebel](https://user-images.githubusercontent.com/54083426/64207670-65865300-ce9d-11e9-8016-6b9e890ff47d.jpg)


* Diese Nebel sind nach einem darin befindlichen System benannt und daher unter Vorbehalt, da die Karte ja voraussichtlich nicht so bleiben wirdn. Es schien mir da jedoch jeweils sehr passend.

**Comment by usox** [comment]
@Huxinator Daten sind drin - sieht soweit ja gut aus, oder?

**Comment by Huxinator** [comment]
Yes, bis auf dass Geminorumkaskade und Atargatiswolke eigentlich eine Wolke sind. Aber das ist für die ja eigentlich egal.

**Comment by LWU86** [comment]
Hab schon einige abgeflogen. Das sieht sehr gut aus.
