### ISSUE TITLE
Kaputte Nahrungsmittelproduktion durch Wetterkontroll-Farmen

### ISSUE THREAD

**Issue by LWU86** [usox/stu3#63]
Die Wetterkontroll-Farmen sind...komisch, um es freundlich auszudrücken.
Ich hab eine davon gebaut, die mir 24 Nahrung abzieht, anstatt sie zu generieren. 
Sobald ich das Gebäude deaktiviere wird mir angezeigt, daß die Produktion wieder bei +/- 0 steht. Allerdings bleibt es dabei nicht. Sobald ich den Koloniebildschirm (ID 1618) verlasse und dann wieder darauf zurückkehre, springt die Anzeige wieder auf -24; obwohl das Gebäude nach wie vor deaktiviert ist.

**Comment by usox** [comment]
Wie im Discord von @Huxinator schon angemerkt, handelt es sich wohl nur um ein Anzeige/Caching Problem. Die Produktion/Effekte auf einem Planeten werden direkt nach einer Aktion (z.b. aktivierung) derzeit nicht aktualisiert.

**Comment by usox** [comment]
Hat sich erledigt
