### ISSUE TITLE
Sammel-Thread Schiffe

### ISSUE THREAD

**Issue by LWU86** [usox/stu3#64]
Wie von Wolv gewünscht, nen gemeinsames Issue für die Fehler bei Schiffen.

-Während man inzwischen wieder von Planeten aus auf Schiffe und von ihnen herunter beamen kann, haben die Transportbuttons in der Schiffsansicht nach wie vor keine Funktion. <--**Funktioniert wieder**

-Selbiges gilt für Karte und Schiffsinformationen. <--**Schiffsinfos sind wieder da, Karte führt zu gatewy timeout**

-Kann auch nur Zufall sein und am Server liegen aber ein Klick auf Aktualisieren schickt das Spiel in ne Warteschleife. Es lädt und lädt und nix passiert.

**Comment by LWU86** [comment]
Schiffe aus Flotten zu entfernen ist ebenfalls nicht möglich.

**Comment by Bielhelm** [comment]
LWU86 aus dem Discord Channel : Ich bin gerade nicht am eigenen Rechner und hab hier den Link zum github nicht, daher die Meldung hier: Ein um 14.38 Uhr fertiggestelltes Schiff (Norway-Klasse) kommt nicht aus der Werft. Es wird weiterhin als im Bau befindlich angezeigt.

**Comment by LWU86** [comment]
Die Demontage von Schiffen funktioniert nicht. Hab es mit jeder Werft außer der Jägerwerft probiert, da ich die gerade nicht habe.

**Comment by LWU86** [comment]
Kleiner Anzeigefehler: Kommt ein Schiff frisch aus der Werft wird das Bild für Alarmstufe grün nicht angezeigt. Zumindest war das bei meiner Norway so.

**Comment by LWU86** [comment]
Auf den Nahbereichssensoren erscheinen keine Schiffe, selbst wenn nachweislich welche vor Ort sind.

**Comment by LWU86** [comment]
Die Schilde werden nicht geladen.

**Comment by usox** [comment]
> -Selbiges gilt für Karte und Schiffsinformationen. <--**Schiffsinfos sind wieder da, Karte führt zu gatewy timeout**

@LWU86 Kannst Du mal schauen? Die Karte funktioniert bei mir (wieder). Wichtig zu wissen ist noch, dass ich zwecks Migrationen die selbst erforschten Kartenfelder loeschen musste.

> -Kann auch nur Zufall sein und am Server liegen aber ein Klick auf Aktualisieren schickt das Spiel in ne Warteschleife. Es lädt und lädt und nix passiert.

Ist das nach wie vor ein Problem?

**Comment by LWU86** [comment]
Die Karte funktioniert und das mit der Warteschleife ist kein zweites Mal passiert.

Dafür ist mir jetzt aufgefallen, daß man nirgendwo mehr andocken kann. Auch nicht an den Stationen der eigenen Rasse; das gibt ne weiße Seite. 
Von Handelsposten runter- oder auf sie raufbeamen funktioniert ebenfalls nicht.

**Comment by LWU86** [comment]
Der Versuch, einem anderen Schiff Energie zu spenden triggert den neuesten Fehlerbildschirm, wie er gestern im Discord verlinkt war.

**Comment by usox** [comment]
Stand jetzt scheint ja das meiste zu passen. Daher mach ich mal zu
