### ISSUE TITLE
Terraformingübersicht läd noch .gif

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3#67]
Wenn man Felder auf der Kolonie terraformt und dann ins Kolonieübersichtmenü geht, wollen in der Terraformingübersicht die Vorher und Nacher Fields noch als .gif geladen werden 
![fields](https://user-images.githubusercontent.com/52821266/67263826-8a647300-f4a9-11e9-9d0d-6b497c103db6.PNG)

**Comment by usox** [comment]
Hm, danke. Scheinbar hat die Suche da nicht geklappt...
