### ISSUE TITLE
Allianzbanner-Format

### ISSUE THREAD

**Issue by Bielhelm** [usox/stu3#8]
150x150 Bildpunkte bei max. 200 kb  für die "Allianzbanner" ist das echt ausreichend? 
Schade auch dass nur png geht. und kein jpg. und auch kein bewegtes gif
(Viele nutzten sehr große, teilweise auch zusammenhängende mehrfache Bilder)

**Comment by usox** [comment]
Genau das ist der Grund. Es gibt immer Leute, die es arg uebertreiben - daher ist das extrem eingeschraenkt. Man kann ggf ueber die Groesse des Bilds noch sprechen, grundlegend sollten wir daran aber nichts aendern

**Comment by Bielhelm** [comment]
HM. OK.
